/*
 * TSW_private.h
 *
 *  Created on: Feb 13, 2016
 *      Author: Home
 */

#ifndef TSW_PRIVATE_H_
#define TSW_PRIVATE_H_

#define INTERNAL_STATES 0
#define EXTERNAL_STATES 1
#define LOW_COUNTER     2
#define HIGH_COUNTER    3


#define TSW_HIGH		1
#define TSW_LOW		    0


#define TSW_MODE         CONC(TSW_MODE0,TSW_MODE1,TSW_MODE2,TSW_MODE3,TSW_MODE4,TSW_MODE5,TSW_MODE6,TSW_MODE7,TSW_MODE8,TSW_MODE9,TSW_MODE10,TSW_MODE11,TSW_MODE12,TSW_MODE13,TSW_MODE14,TSW_MODE15)
#define CONC(TSW_MODE0,TSW_MODE1,TSW_MODE2,TSW_MODE3,TSW_MODE4,TSW_MODE5,TSW_MODE6,TSW_MODE7,TSW_MODE8,TSW_MODE9,TSW_MODE10,TSW_MODE11,TSW_MODE12,TSW_MODE13,TSW_MODE14,TSW_MODE15)   CONC_HELP(TSW_MODE15,TSW_MODE14,TSW_MODE13,TSW_MODE12,TSW_MODE11,TSW_MODE10,TSW_MODE9,TSW_MODE8,TSW_MODE7,TSW_MODE6,TSW_MODE5,TSW_MODE4,TSW_MODE3,TSW_MODE2,TSW_MODE1,TSW_MODE0)
#define CONC_HELP(TSW_MODE15,TSW_MODE14,TSW_MODE13,TSW_MODE12,TSW_MODE11,TSW_MODE10,TSW_MODE9,TSW_MODE8,TSW_MODE7,TSW_MODE6,TSW_MODE5,TSW_MODE4,TSW_MODE3,TSW_MODE2,TSW_MODE1,TSW_MODE0)   0b##TSW_MODE15##TSW_MODE14##TSW_MODE13##TSW_MODE12##TSW_MODE11##TSW_MODE10##TSW_MODE9##TSW_MODE8##TSW_MODE7##TSW_MODE6##TSW_MODE5##TSW_MODE4##TSW_MODE3##TSW_MODE2##TSW_MODE1##TSW_MODE0
#endif /* TSW_PRIVATE_H_ */
