/*
 * UART_conig.h
 *
 *  Created on: Mar 27, 2016
 *      Author: Home
 */

#ifndef USART_CONIG_H__
#define USART_CONIG_H__


#define USART_SYNCH_MODE		USART_ASYNCH// USART_SYNC
#define USART_SPEED_MODE		USART_NORMAL_SPEED//USART_DOUBLE_SPEED
#define USART_BAUD				9600
#define USART_FOSC				FOUR_MEGA
#define USART_TRANSMIT			USART_ENABLE//USART_DISBALE
#define USART_RECIEVE			USART_ENABLE//USART_DISBALE
#define USART_CHAR_SIZE			USART_8_Bit_CHAR//USART_6_Bit_CHAR,USART_7_Bit_CHAR,USART_5_Bit_CHAR,USART_8_Bit_CHAR
#define USART_PARITY_MODE		USART_NO_PARITY//USART_EVEN_PARITY,USART_ODD_PARITY
#define USART_STOPBIT			USART_1_STOPBIT//USART_2_STOPBIT
#define USART_RECIEVE_INT		USART_RECIEVER_ENABLE  //USART_RECIEVER_DISABLE
#define USART_TRANSMITER_INT	USART_TRANSMITER_ENABLE//USART_TRANSMITER_DISABLE
#endif
