/*
 * SPI_config.h
 *
 *  Created on: Apr 7, 2016
 *      Author: Home
 */

#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

#define SLAVE_MODE				SPI_MASTER//SPI_SLAVE
#define SPI_PRESCALAR			SPI_Fosc128 // SPI_Fosc4,SPI_Fosc16 SPI_Fosc64 SPI_Fosc128
#define SPI_ENABLE				SPI_ENABLE_ON//SPI_DISABLE_OFF
#define SPI_DOUBLE_SPEED		SPI_DOUBLE_SPEED_MODE_OFF//SPI_DOUBLE_SPEED_MODE_ON
#define SPI_OPERATING_LEVEL		SPI_IDLE_LOW//SPI_IDLE_HIGH
#define SPI_SAMPLING_EDGE		SPI_RISING//SPI_FALLING
#define SPI_INT_ENABLE			SPI_INT_ON//SPI_INT_OFF
#define SPI_DATA_ORDER			SPI_LSB_FISRT//SPI_MSB_FISRT



#endif /* SPI_CONFIG_H_ */
